//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab4_MusicStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Album
    {
        public int AlbumID { get; set; }
        public string Title { get; set; }
        public double Price { get; set; }
        public string AlbumUrl { get; set; }
        public int Genre_ID { get; set; }
        public int Artist_ID { get; set; }
    }
}
