//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab4_MusicStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdeDetal
    {
        public int OrderDetailIID { get; set; }
        public int Order_ID { get; set; }
        public int Album_ID { get; set; }
        public int Quantity { get; set; }
        public double Total_OD { get; set; }
    }
}
